#import = ["~/.config/alacritty/themes/themes/tokyo-night-storm.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
normal.family = "0xProto Nerd Font Mono"
size = 14
offset.y = 2
glyph_offset.y = 1
