#import = ["~/.config/alacritty/themes/themes/tokyo-night-storm.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "SemiLight" }
bold = { family = "CaskaydiaMono Nerd Font", style = "SemiBold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "SemiLight Italic" }
size = 14
offset.y = 2
glyph_offset.y = 1
