#!/usr/bin/env bash

yabai -m config layout bsp
yabai -m config window_placement second_child

# yabai -m window_shadow on
# yabai -m active_window_opacity 1.0
# yabai -m normal_window_opacity 0.90
# Padding
yabai -m config top_padding 3
yabai -m config bottom_padding 3
yabai -m config left_padding 3
yabai -m config right_padding 3
yabai -m config window_gap 5
yabai -m config auto_balance off
yabai -m config split_ratio 0.5
yabai -m config window_shadow off

#
## setup spaces
#
for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 6)'); do
  yabai -m space --destroy 7
done

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx: $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 social
setup_space 2 web
setup_space 3 terminal
setup_space 4 code
setup_space 5 media
setup_space 6 other

yabai -m rule --add app="^IntelliJ IDEA" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title=".*\[(.*)\].*" manage=on

# mouse settings
# yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
# Disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Calendar$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
