unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-a
set -g mouse on
setw -g mode-keys vi
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

bind - split-window -v
bind _ split-window -h

bind Enter copy-mode 

bind-key "T" run-shell "sesh connect \"$(
  sesh list -t --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""

set -g base-index 1
set -g pane-base-index 1

set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "weather"
set -g @dracula-show-powerline true 
set -g @dracula-show-flags true
set -g @dracula-show-fahrenheit false
set -g @dracula-show-left-icon session
set -g @dracula-show-location false
set -g @dracuka-show-fahrenheit false

set -g status-position top


run -b '~/.config/tmux/plugins/tpm/tpm'



